version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:1.22.0
    ports:
      - "8000:8000"
  
  php:
    depends_on:
      - dynamodb-local
    image: mcr.microsoft.com/vscode/devcontainers/php:8.1
    container_name: php
    environment:
      AWS_ACCESS_KEY_ID: 'none'
      AWS_SECRET_ACCESS_KEY: 'none'
