on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: PHP ${{ matrix.php-version }} / async-aws/dynamo-db ${{ matrix.async-aws-dynamo-db }}
    runs-on: ubuntu-latest
    services:
      dynamodb-local:
        image: amazon/dynamodb-local:1.22.0
        ports:
          - 8000:8000/tcp
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '8.2'
            async-aws-dynamo-db: '^1.3.0'
          - php-version: '8.2'
            async-aws-dynamo-db: '^2.0.0'
          - php-version: '8.2'
            async-aws-dynamo-db: '^3.0.0'
          - php-version: '8.3'
            async-aws-dynamo-db: '^1.3.0'
          - php-version: '8.3'
            async-aws-dynamo-db: '^2.0.0'
          - php-version: '8.3'
            async-aws-dynamo-db: '^3.0.0'
          - php-version: '8.4'
            async-aws-dynamo-db: '^1.3.0'
          - php-version: '8.4'
            async-aws-dynamo-db: '^2.0.0'
          - php-version: '8.4'
            async-aws-dynamo-db: '^3.0.0'
          - php-version: '8.5'
            async-aws-dynamo-db: '^1.3.0'
          - php-version: '8.5'
            async-aws-dynamo-db: '^2.0.0'
          - php-version: '8.5'
            async-aws-dynamo-db: '^3.0.0'
    env: 
      AWS_ACCESS_KEY_ID: 'none'
      AWS_SECRET_ACCESS_KEY: 'none'
      DYNAMODB_ENDPOINT: 'http://127.0.0.1:8000'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          coverage: xdebug

      - name: Validate composer.json
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v6
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-dynamodb-${{ matrix.async-aws-dynamo-db }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-dynamodb-${{ matrix.async-aws-dynamo-db }}-

      - name: Install dependencies
        run: |
          composer require async-aws/dynamo-db:${{ matrix.async-aws-dynamo-db }} --no-update
          composer update --prefer-dist --no-progress

      - name: Run phpunit
        run: composer run-script phpunit

      - name: Run phpstan
        run: composer run-script phpstan

  ecs:
    name: ECS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer
          coverage: none

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v6
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.4-ecs-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-8.4-ecs-

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Run ECS
        run: vendor/bin/ecs check --config ecs.php

  infection:
    name: Infection
    runs-on: ubuntu-latest
    services:
      dynamodb-local:
        image: amazon/dynamodb-local:1.22.0
        ports:
          - 8000:8000/tcp
    env:
      AWS_ACCESS_KEY_ID: 'none'
      AWS_SECRET_ACCESS_KEY: 'none'
      DYNAMODB_ENDPOINT: 'http://127.0.0.1:8000'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer
          coverage: xdebug

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v6
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.4-infection-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-8.4-infection-

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Run Infection
        run: composer run-script infection
